theme: jekyll-theme-slate
title: Duplicate Finder
description: Duplicate finder is a tool for discovering and tracking near and exact duplicates in documents
markdown: kramdown
kramdown:
   auto_ids: true